[package]
name = "zk_deck_shuffle_bindings"
version = "0.1.0"
edition = "2024"

[lib]
name = "zk_deck_shuffle_bindings"
path = "lib.rs"

[dependencies]
leo-bindings.workspace = true

[build-dependencies]
leo-bindings-core = { git = "https://github.com/henrikkv/leo-bindings" }
serde_json = "1"
